package com.example.CheckInApi.Controller;

import com.example.CheckInApi.modal.Profile;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import com.example.CheckInApi.repository.ProfileRepository;

@RestController // This means that this class is a Controller
public class ProfileController {
    @Autowired // This means to get the bean called profileRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ProfileRepository profileRepository;

    @PostMapping(path="/profile") // Map ONLY POST Requests
    public @ResponseBody String addNewProfile (@RequestParam String username
            , @RequestParam String password, @RequestParam String role) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Profile n = new Profile();
        n.setUsername(username);
        n.setPassword(password);;
        n.setRole(role);
        profileRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/profile")
    public @ResponseBody Iterable<Profile> getAllProfiles() {
        // This returns a JSON or XML with the users
        return profileRepository.findAll();
    }
}